# Generated by Django 5.2.1 on 2025-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_remove_category_image_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
