# Generated by Django 5.2.1 on 2025-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
    ]
